### ISSUE TITLE
Nuevo Campo en OptionPerVote

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#10]
Durante el desarrollo de los sistemas de recuento se detectó una necesidad de cambio en el modelo de la BD que pudiera aportar información sobre la preferencia del votante en cada respuesta. Para ello se ha planteado un campo de tipo integer con valor desde 0 hasta N, definido en la cabina de votación.

Ya que su subsistema es el encargado de almacenar la información relativa a los votos necesitamos su confirmación junto a las ya recibidas por parte de integración y cabina de votaciones.

**Comment by Silverath** [comment]
Desde almacemamiento de votos le damos nuestra confirmación a ese incremento.
