### ISSUE TITLE
Proporcionar número de votantes de una votación

### ISSUE THREAD

**Issue by jorgegarciax2** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#14]
Desde redes sociales y para ofrecer la funcionalidad de compartir un balance de participación de los votantes en una votación, necesitamos saber si existiría la posibilidad de que nos proporcionaseis el número de votantes de una votación.

El objetivo sería que el equipo de Almacenamiento de Votos implementase un contador a la hora de que los usuarios realicen una votación, de forma que podamos consultar dicho dato.

Desde integración nos han pedido llegar a un acuerdo. Ellos ya se han encargado de incluir el atributo en la tabla poll de la base de datos.

**Comment by Silverath** [comment]
Desde almacenamiento de votos confirmamos la colaboración por nuestra parte respecto a la nueva funcionalidad.
