### ISSUE TITLE
Cifrado de la información

### ISSUE THREAD

**Issue by juasanpar** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#15]
El cifrado de la información presenta un problema, del modo en el que se está planteando impide que se utilice el script de población de la BD proporcionado por integración para el testing, por lo debe ser lo último en implementarse en el código final.

**Comment by Silverath** [comment]
Estamos teniendo problemas con la implementación ya que nos ha dado problemas el almacenamiento de los votos simple por lo que, aunque esté en continuo desarrollo de forma paralela, se aplazará para el Milestone 4.

**Comment by Silverath** [comment]
https://github.com/Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1/commit/f771b384af1588a74526e899c8a7060bdbf71522

**Comment by juasanpar** [comment]
He testeado el cifrado y salta un error al intentar cifrar el usuario.

**Comment by juasanpar** [comment]
[Realizado](https://github.com/Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1/commit/abe09648f515df391e8b6c55b230d56d745da465)
