### ISSUE TITLE
Voto único por usuario 

### ISSUE THREAD

**Issue by Silverath** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#20]
Solo estará permitido votar una vez por usuario en una misma votación.

**Comment by juasanpar** [comment]
Voto único por usuario implementado y testeado.
`def checkOnlyOneVotePerUser (id_poll, id_user):
    username = UserAccount.objects.get(id = id_user).username
    pollT = Poll.objects.get(id = id_poll)
    questions = Question.objects.filter(poll = pollT)
    
    for questionT in questions:
        questionOptions = QuestionOption.objects.filter(question = questionT)
        
        for questionOptionT in questionOptions:
            optionPerVotes = OptionPerVote.objects.filter(question_option = questionOptionT)

            for optionPerVote in optionPerVotes:
                if optionPerVote.vote.token == username:
                    raise MoreThanOneVoteException("El usuario ya ha participado en esta votacion")`
