### ISSUE TITLE
Preferencia de las opciones de las preguntas múltiples

### ISSUE THREAD

**Issue by Silverath** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#21]
Algunas preguntas tendrán una prioridad que el votante asignará. En función de eso, tendremos que manejar el almacenamiento de forma que se almacenen correctamente las prioridades de las preguntas que tengan las mismas.

**Comment by juasanpar** [comment]
Cabina ha notificado que no es necesario tratar con prioridades.
