### ISSUE TITLE
Automatización de la construcción

### ISSUE THREAD

**Issue by VictoriaCalbet** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#28]

**Comment by danrodagu** [comment]
13a44a27e4e09500257334f9f7041c5dfc52efd2

**Comment by danrodagu** [comment]
Añadido .gitignore para la correcta subida del archivo .travis.yml: commit 3d15b0f21984296b7f13e1345b47a9b17ef50ee9

**Comment by danrodagu** [comment]
.travis.yml v2: commit 6dd5447d023b932fd416b4e17b903fffd8dcf83b

**Comment by danrodagu** [comment]
.travis.yml v2.1: fe2dfb18919955b804512a0ff54770e5d40ccdbb

**Comment by danrodagu** [comment]
.travis.yml v3: 8d70b7e8f7a2c1f11b6dee8a198d9073fdfdbcc4

**Comment by danrodagu** [comment]
Corregida errata en archivo travis: acbd8e20f3ac5624edbf2afa62bab658001d1f35

**Comment by danrodagu** [comment]
.travis.yml v4: 10c20ea3f296e2aeb40cd10454169699bcd880a5

**Comment by danrodagu** [comment]
.travis.yml v4.1: b11429be5f6bdfa6347b47293dd038cc81f7cb58

**Comment by danrodagu** [comment]
Archivo travis modificado: 3a028c6ebe8580408396f43da65d5f7bba4b1f12

**Comment by danrodagu** [comment]
Eliminada carpeta innecesaria 'Documentación' en esta rama: cb2ab9dd1d9f887e55d81aa4a7e5fc71eca5d357

**Comment by danrodagu** [comment]
Merge remote-tracking branch 'origin/Build': fa72644d6ae16376acbd974908469791155d9cff

Commit que finaliza esta issue.
