### ISSUE TITLE
Error al guardar el voto

### ISSUE THREAD

**Issue by earthtofran** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#33]
1. Inicio sesión y soy redireccionado a la lista de votaciones.
2. Pulso en "votar" sobre una de las votaciones
3. Relleno los datos necesarios, pulso en enviar y se muestra por pantalla "el atributo voto_id no puede ser null"

#Resultado esperado:

Se esperaba que se indicara que se ha guardado correctamente.

#Resultado obtenido:

No se guarda el voto.

**Comment by JuanpaG94** [comment]
Se ha recibido el fallo. A la espera de propuesta de solución. Gracias.

**Comment by juasanpar** [comment]
Necesito más información para poder reparar el error, como qué método se está utilizando cuando da dicho error, qué parámetros se le están añadiendo, etc. La traza tal cual del fallo sería ideal tenerla también.

Información que puede ser útil:
-Borrad todo los votos existentes en la bd y trabajar solo con los creados a través de nuestra librería, pues el RSA da conflicto con los votos que ya se encuentran en la BD y no lo implementan.
-Comprobad que cuando se inserta el voto, las question options pertenecen a la votación de destino, ya que el sistema comprueba que éstas estén en la poll antes de insertar el voto y si no lanza una excepción.

**Comment by JuanpaG94** [comment]
Procedo a cerrar la incidencia, el sistema funciona correctamente y no se ha proporcionado más información por parte de la persona que ha abierto dicha incidencia.
