### ISSUE TITLE
Conexión con la base de datos

### ISSUE THREAD

**Issue by Silverath** [Proyecto-EGC-G1/Almacenamiento-Votos-EGC-G1#7]
Conectar la base de datos facilitada por el equipo de integración con nuestro proyecto

**Comment by Silverath** [comment]
Se debe de estudiar cómo conectar el modelo con Xampp.

**Comment by juasanpar** [comment]
Ya se ha conseguido conectar la aplicación Django con Xampp

**Comment by JuanpaG94** [comment]
Marco como cerrado entonces chicos.
